# Required Skipper info
SKIPPER_CONFIG: /tscc/projects/ps-yeolab4/software/flipper/1.0.0/bin/flipper/example/yeo_lab_internal_example_skipper_config.yaml
SKIPPER_OUTPUT: /tscc/projects/ps-yeolab4/software/flipper/1.0.0/bin/flipper/example/example_skipper_run

# Required Output path
WORKDIR: /tscc/nfs/home/YOUR_USERNAME/scratch/flipper_test
TOOLS: /tscc/projects/ps-yeolab4/software/flipper/1.0.0/bin/flipper/tools 

# Required Differential comparison, we always have (TREATMENT/CONTROL), so look for + log2FC for up-regulation in TREATMENT.
CONTROL: DMSO 
TREATMENT: 10R

# Required DIBS parameters, for normalization: one of either MOR, EDA_full, EDA_median, or EDA_loess
LOG2FC_THRESHOLD: 1
PVAL_THRESHOLD: 0.05
SUBSTRATE_CONTROL: INf
NORMALIZATION: MOR_hier # one of either MOR, EDA_full, EDA_median, or EDA_loess
SPECIES: Homo sapiens

# # Specific methods for EDAseq (will be ignored if method is not EDA or EDA_hier). 
# GC_METHOD: full # Options: loess, median, upper, full
# LENGTH_METHOD: full # Options: loess, median, upper, full
# BETWEEN_METHOD: full # Options: median, upper full

# Optional DIBS parameters, set true/false. For RNASEQ, simply delete the RNASEQ parameter if no RNASEQ DESeq2 data will be used. See example under Examples folder.
MAKE_BIGWIGS: False
HOMER: False
METADENSITY: False

# Specific methods for metadensity (will be ingorned if metadensity is not true)
# FEATURES: "first_exon,exon,intron,last_exon" # Some combination of 'five_prime_UTR', 'first_exon', 'exon', 'intron', 'last_exon', 'CDS', 'three_prime_UTR'